app:
  level: "INFO"
  port: 8088
orderly:
  account_id: '0x7800bdce2bb08e70c0981a5c11b34b9da28097949dfedec837ad8838b710aa9b'
  rest_endpoint: 'https://dev-api-v2.orderly.org'
  ws_public_endpoint: 'wss://dev-ws-v2.orderly.network/ws/stream/'
  ws_private_endpoint: 'wss://dev-ws-private-v2.orderly.network/v2/ws/private/stream/'
  max_notional: 1000
  liquidation_symbols: ['PERP_BTC_USDC', 'PERP_ETH_USDC', 'PERP_NEAR_USDC', 'PERP_WOO_USDC']
