app:
  level: "INFO"
  port: 8088
orderly:
  account_id: '0x4546c076e1d6ae0013195316c0c7b405699c839bb760a42f41005103134dcf3f'
  rest_endpoint: 'https://api-evm.orderly.network'
  ws_public_endpoint: 'wss://ws-evm.orderly.network'
  ws_private_endpoint: 'wss://ws-private-evm.orderly.network'
  claim_percent: 0.001
  symbol_qty:
    # notional range: 100U ~ 1000U
    - ['PERP_BTC_USDC', [0.002, 0.02]]
    - ['PERP_ETH_USDC', [0.04, 0.4]]
    - ['PERP_NEAR_USDC', [46, 460]]
    - ['PERP_WOO_USDC', [425, 4250]]
