app:
  # proxy: 'http://127.0.0.1:7890'
  port: 8088
orderly:
  account_id: '0x4546c076e1d6ae0013195316c0c7b405699c839bb760a42f41005103134dcf3f'
  rest_endpoint: 'https://testnet-api-evm.orderly.org'
  ws_public_endpoint: 'wss://testnet-ws-evm.orderly.network/ws/stream/'
  ws_private_endpoint: 'wss://testnet-ws-private-evm.orderly.network/v2/ws/private/stream/'
