app:
  level: "INFO"
  port: 8088
  proxy: 'http://127.0.0.1:7890'
orderly:
  account_id: '0x39f80501b0c86b13dab33bf0a4a7639dfc87d8143ec6b97a713b2ceda15cd651'
  rest_endpoint: 'https://testnet-api-evm.orderly.org'
  ws_public_endpoint: 'wss://testnet-ws-evm.orderly.network/ws/stream/'
  ws_private_endpoint: 'wss://testnet-ws-private-evm.orderly.network/v2/ws/private/stream/'
  max_notional: 11000
  liquidation_symbols: ['PERP_APT_USDC', 'PERP_ARB_USDC', 'PERP_BCH_USDC', 'PERP_BNB_USDC', 'PERP_BTC_USDC', 'PERP_ETH_USDC', 'PERP_LINK_USDC', 'PERP_MATIC_USDC', 'PERP_OP_USDC', 'PERP_SOL_USDC', 'PERP_SUI_USDC', 'PERP_TIA_USDC', 'PERP_WOO_USDC', 'PERP_XRP_USDC']
woo:
  symbol_map:
    - ['PERP_APT_USDC', 'APT/USDT:USDT']
    - ['PERP_ARB_USDC', 'ARB/USDT:USDT']
    - ['PERP_BCH_USDC', 'BCH/USDT:USDT']
    - ['PERP_BNB_USDC', 'BNB/USDT:USDT']
    - ['PERP_BTC_USDC', 'BTC/USDT:USDT']
    - ['PERP_ETH_USDC', 'ETH/USDT:USDT']
    - ['PERP_LINK_USDC', 'LINK/USDT:USDT']
    - ['PERP_MATIC_USDC', 'MATIC/USDT:USDT']
    - ['PERP_OP_USDC', 'OP/USDT:USDT']
    - ['PERP_SOL_USDC', 'SOL/USDT:USDT']
    - ['PERP_SUI_USDC', 'SUI/USDT:USDT']
    - ['PERP_TIA_USDC', 'TIA/USDT:USDT']
    - ['PERP_WOO_USDC', 'WOO/USDT:USDT']
    - ['PERP_XRP_USDC', 'XRP/USDT:USDT']
  testnet: true
  api_key: 'ZooFkw0izItvBnobplhqRw=='
  secret_key: 'VOWF62QUQ7KBKPTH5CO4PU26RDMK'
  app_id: 'dce5d86f-e373-42f7-8afd-f743e18617ca'
